runtime: go111

main: web

handlers:
- url: /static
  static_dir: frontend/dist
  secure: always

- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?frontend/node_modules/.*$
- ^(.*/)?frontend/src/.*$
- ^(.*/)?frontend/rollup\.config\.js$
- ^(.*/)?frontend/.*\.json$
- ^(.*/)?frontend/.*\.lock$
- ^(.*/)?frontend/.*\.md$
